use carpio_47375;
-- SENTENCIAS SENTENCIAS SENTENCIAS SENTENCIAS SENTENCIAS SENTENCIAS SENTENCIAS SENTENCIAS


USE mysql ;

-- Crear un Usuario que tenga permiso de solo lectura sobre todas las tablas del esquema Carpio_47375


CREATE USER IF NOT EXISTS 'usuario1'@'localhost' identified by '47375'; -- USER AND PASSWORD CREATION


GRANT SELECT ON  carpio_47375.appointment  TO 'usuario1'@'localhost' ; -- READ PERMISSION IN THE SCHEME CARPIO_47375 ABOUT THE APPOINTMENTS TABLE
GRANT SELECT ON  carpio_47375.customer TO 'usuario1'@'localhost' ; -- READ PERMISSION IN THE CARPIO_47375 SCHEMA ON THE CUSTOMER TABLE
GRANT SELECT ON  carpio_47375.log_audit_position  TO 'usuario1'@'localhost' ; -- READ PERMISSION IN THE CARPIO_47375 SCHEME ABOUT THE AUDIT TABLE
GRANT SELECT ON  carpio_47375.log_historic_position  TO 'usuario1'@'localhost' ; -- READ PERMISSION IN THE SCHEME CARPIO_47375 ABOUT THE HISTORY TABLE
GRANT SELECT ON  carpio_47375.payment  TO 'usuario1'@'localhost' ; -- READ PERMISSION IN THE CARPIO_47375 SCHEMA ON THE PAYMENT TABLE
GRANT SELECT ON  carpio_47375.payment_type  TO 'usuario1'@'localhost' ; -- READ PERMISSION IN THE CARPIO_47375 SCHEMA ON THE PAYMENT_TYPE TABLE
GRANT SELECT ON  carpio_47375.position  TO 'usuario1'@'localhost' ; -- READ PERMISSION IN THE CARPIO_47375 SCHEME ON THE POSITION TABLE
GRANT SELECT ON  carpio_47375.service  TO 'usuario1'@'localhost' ; -- READ PERMISSION IN THE CARPIO_47375 SCHEME ON THE SERVICE TABLE
GRANT SELECT ON  carpio_47375.worker  TO 'usuario1'@'localhost' ; -- READ PERMISSION IN THE CARPIO_47375 SCHEME ON THE WORKER TABLE


-- crear un usuario que tenga permiso de lectura, inserción y modificación sobre todas las tablas del esquema Carpio_47375 (SELECT, INSERT Y UPDATE)

CREATE USER IF NOT EXISTS 'usuario2'@'localhost' identified by '47375' ;  -- USER AND PASSWORD CREATION


GRANT SELECT , INSERT , UPDATE ON carpio_47375.appointment TO 'usuario2'@'localhost'  ; -- READING, INSERTION AND MODIFICATION PERMISSION IN THE SCHEME Carpio_47375 ON THE appointment TABLE
GRANT SELECT , INSERT , UPDATE ON carpio_47375.customer TO 'usuario2'@'localhost'  ; -- READING, INSERTION AND MODIFICATION PERMISSION IN THE SCHEME Carpio_47375 ON THE CUSTOMER TABLE
GRANT SELECT , INSERT , UPDATE ON carpio_47375.log_audit_position TO 'usuario2'@'localhost'  ; -- READING, INSERTION AND MODIFICATION PERMISSION IN THE SCHEME Carpio_47375 ON THE log_audit_position TABLE
GRANT SELECT , INSERT , UPDATE ON carpio_47375.log_historic_position TO 'usuario2'@'localhost'  ; -- READING, INSERTION AND MODIFICATION PERMISSION IN THE SCHEME Carpio_47375 ON THE log_historic_position TABLE
GRANT SELECT , INSERT , UPDATE ON carpio_47375.payment TO 'usuario2'@'localhost'  ; -- READ, INSERTION AND MODIFICATION PERMISSION IN THE SCHEME Carpio_47375 ON THE PAYMENT TABLE
GRANT SELECT , INSERT , UPDATE ON carpio_47375.payment_type TO 'usuario2'@'localhost'  ; -- READ, INSERTION AND MODIFICATION PERMISSION IN THE SCHEME Carpio_47375 ON THE PAYMENT_TYPE TABLE
GRANT SELECT , INSERT , UPDATE ON carpio_47375.position TO 'usuario2'@'localhost'  ; -- READING, INSERTION AND MODIFICATION PERMISSION IN THE SCHEME Carpio_47375 ON THE POSITION TABLE
GRANT SELECT , INSERT , UPDATE ON carpio_47375.service TO 'usuario2'@'localhost'  ; -- READING, INSERTION AND MODIFICATION PERMISSION IN THE SCHEME Carpio_47375 ON THE SERVICE TABLE
GRANT SELECT , INSERT , UPDATE ON carpio_47375.worker TO 'usuario2'@'localhost'  ; -- READING, INSERTION AND MODIFICATION PERMISSION IN THE SCHEME Carpio_47375 ON THE WORKER TABLE
